import { createTransport } from "nodemailer";
import { MailOptions } from "nodemailer/lib/json-transport";
import serverConfig from "#src/config/serverConfig";

const transporter = createTransport({
  service: "gmail",
  pool: true,
  auth: {
    type: "OAuth2",
    user: serverConfig.EMAIL_SENDER,
    clientId: serverConfig.GOOGLE_CLIENT_ID,
    clientSecret: serverConfig.GOOGLE_CLIENT_SECRET,
    refreshToken: serverConfig.GOOGLE_REFRESH_TOKEN,
  },
});

/**
 * Sends an email using the configured transporter.
 * @param mailOptions - The mail options object generated by generateMailOptions.
 * @returns The info object from nodemailer.sendMail.
 * @throws Error if sending fails.
 */

export const sendEmails = async (mailOptions: MailOptions) => {
  try {
    const info = await transporter.sendMail(mailOptions);
    return info;
  } catch (error: any) {
    throw new Error(error.message);
  }
};
