import { createTransport } from "nodemailer";
import { MailOptions } from "nodemailer/lib/json-transport";

const transporter = createTransport({
  service: "gmail",
  pool: true,
  auth: {
    type: "OAuth2",
    user: "realemail@gmail.com",
    clientId: "",
    clientSecret: "",
    refreshToken: "",
  },
});

/**
 * Sends an email using the configured transporter.
 * @param mailOptions - The mail options object generated by generateMailOptions.
 * @returns The info object from nodemailer.sendMail.
 * @throws Error if sending fails.
 */

export const sendEmails = async (mailOptions: MailOptions) => {
  try {
    const info = await transporter.sendMail(mailOptions);
    return info;
  } catch (error: any) {
    throw new Error(error.message);
  }
};
